//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.SearchCoach {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.SearchCoach.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Coach.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer!.
        /// </summary>
        public static string CorrectAnswerText {
            get {
                return ResourceManager.GetString("CorrectAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! something went wrong, please try again later..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging Extension only supports in Team Scope..
        /// </summary>
        public static string PersonalScopeErrorMessage {
            get {
                return ResourceManager.GetString("PersonalScopeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Search Coach.
        /// </summary>
        public static string PersonalScopeWelcomeCardDeepLinkButtonText {
            get {
                return ResourceManager.GetString("PersonalScopeWelcomeCardDeepLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching the internet is an important skill for students to master. Your class will be using the Search Coach app to learn basic concepts and try out different types of searches. I may occasionally send out questions to quiz you on what you&apos;ve learned. When I do, just reply to me and your teacher will see your answer. Happy searching!.
        /// </summary>
        public static string PersonalScopeWelcomeCardHeadingText {
            get {
                return ResourceManager.GetString("PersonalScopeWelcomeCardHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there! I&apos;m the Search Coach bot!.
        /// </summary>
        public static string PersonalScopeWelcomeCardTitleText {
            get {
                return ResourceManager.GetString("PersonalScopeWelcomeCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected question has already been sent to all team members..
        /// </summary>
        public static string QuestionAlreadySentErrorMessageText {
            get {
                return ResourceManager.GetString("QuestionAlreadySentErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Answer:.
        /// </summary>
        public static string QuestionAnswerCardCorrectAnswerMessageText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardCorrectAnswerMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string QuestionAnswerCardOpenUrlButtonText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardOpenUrlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use search coach.
        /// </summary>
        public static string QuestionAnswerCardShowCardTextBoxText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardShowCardTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string QuestionAnswerCardSubmitActionButtonText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardSubmitActionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note from your teacher:.
        /// </summary>
        public static string QuestionAnswerCardSubmitNoteText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardSubmitNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search coach.
        /// </summary>
        public static string QuestionAnswerCardTextBoxLabelText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardTextBoxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for taking the quiz!.
        /// </summary>
        public static string QuestionAnswerCardThankNoteText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardThankNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just sent you a question through search coach.
        /// </summary>
        public static string QuestionAnswerCardUserSendMessageText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardUserSendMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We suggest you use Search Coach to learn about this concept..
        /// </summary>
        public static string QuestionAnswerCardWrongAnswerMessageText {
            get {
                return ResourceManager.GetString("QuestionAnswerCardWrongAnswerMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string QuestionListTaskModuleTitle {
            get {
                return ResourceManager.GetString("QuestionListTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one question from the list: .
        /// </summary>
        public static string QuestionsCardBodyTitleText {
            get {
                return ResourceManager.GetString("QuestionsCardBodyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string QuestionsCardSendButtonText {
            get {
                return ResourceManager.GetString("QuestionsCardSendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TaskModuleErrorTitle {
            get {
                return ResourceManager.GetString("TaskModuleErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string TaskModuleTitle {
            get {
                return ResourceManager.GetString("TaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is not installed in this team..
        /// </summary>
        public static string TeamScopeErrorMessage {
            get {
                return ResourceManager.GetString("TeamScopeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching the internet is an important skill for students to master. Your class will be using the Search Coach app to learn basic concepts and try out different types of searches. I may occasionally send out questions to quiz you on what you&apos;ve learned. When I do, just reply to me and your teacher will see your answer. Happy searching!.
        /// </summary>
        public static string TeamScopeWelcomeCardHeadingText {
            get {
                return ResourceManager.GetString("TeamScopeWelcomeCardHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there! I&apos;m the Search Coach bot!.
        /// </summary>
        public static string TeamScopeWelcomeCardTitleText {
            get {
                return ResourceManager.GetString("TeamScopeWelcomeCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect answer.
        /// </summary>
        public static string WrongAnswerText {
            get {
                return ResourceManager.GetString("WrongAnswerText", resourceCulture);
            }
        }
    }
}
